title: "My Blog"
description: "Blog powered by GitHub Issues"
theme: minima
plugins:
  - jekyll-feed
collections:
  posts:
    output: true  # This makes sure posts get their own pages
    permalink: /:year/:month/:day/:title/