title: "My Blog"
description: "A blog powered by GitHub Issues"
baseurl: ""
url: "https://yourusername.github.io"

# Collections: Define 'posts/' as a collection of blog posts
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Enable Markdown and Syntax Highlighting
markdown: kramdown
highlighter: rouge

# Exclude these from Jekyll processing
exclude:
  - README.md
  - .github/