name: Convert Issues to Blog Posts

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue data
        run: |
          mkdir -p posts  # Ensure the 'posts/' directory exists

          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_DATE="${{ github.event.issue.created_at }}"
          ISSUE_TAGS="$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name' | tr '\n' ', ')"

          # Sanitize title for filename (lowercase, hyphenated)
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')

          # Escape double quotes in title
          ESCAPED_TITLE=$(echo "$ISSUE_TITLE" | sed 's/"/\\"/g')

          # Create Markdown file
          POST_PATH="posts/${ISSUE_DATE:0:10}-$SAFE_TITLE.md"
          cat <<EOF > "$POST_PATH"
---
title: "$ESCAPED_TITLE"
date: $ISSUE_DATE
tags: [$ISSUE_TAGS]
permalink: /${ISSUE_DATE:0:10}-$SAFE_TITLE/
layout: post
---

$ISSUE_BODY
EOF

      - name: Commit new post
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posts/
          git commit -m "New blog post from issue #${{ github.event.issue.number }}: $ISSUE_TITLE" || exit 0
          git push
