name: Convert Issues to Blog Posts

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python Markdown Parser
        run: pip install commonmark

      - name: Convert Issue to HTML
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          # Convert Markdown to HTML using commonmark
          BODY_HTML=$(echo "$ISSUE_BODY" | python -c "import sys, commonmark; print(commonmark.commonmark(sys.stdin.read()))")

          # Generate an HTML file
          POST_FILE="posts/${ISSUE_NUMBER}.html"
          mkdir -p posts
          cat <<EOF > $POST_FILE
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>$ISSUE_TITLE</title>
          </head>
          <body>
              <h1>$ISSUE_TITLE</h1>
              <div>$BODY_HTML</div>
          </body>
          </html>
          EOF

      - name: Commit and push post
        run: |
          git config --global user.name "yansklyarenko"
          git config --global user.email "yansklyarenko@gmail.com"
          git add posts/
          git commit -m "Add blog post: $ISSUE_TITLE" || exit 0
          git push origin HEAD:main
